name: mhu_dart_protoc
version: 1.0.1
repository: https://github.com/maprohu/mhu_dart_protoc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  mhu_dart_commons:
    path: ../mhu_dart_commons
  mhu_dart_sourcegen:
    path: ../mhu_dart_sourcegen
  mhu_dart_annotation:
    path: ../mhu_dart_annotation

dependencies:
  mhu_dart_commons: ^1.0.9
  mhu_dart_sourcegen: ^1.0.1

  recase: ^4.1.0
  fast_immutable_collections: ^9.1.5
  collection: ^1.17.1
  protobuf: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
